version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresql
    networks:
      - my-network
    ports:
      - 9000:9000 # metric
      - 8080:8080 # main http
      - 6060:6060 # gateway
      - 3030:3030 # grpc
    environment:
      - DB_HOST=postgresql
      - DB_PASSWORD=password
      - DB_USERNAME=user
      - DB_NAME=avito

  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=avito
      - POSTGRES_HOST_AUTH_METHOD=trust  
    ports:
      - 5432:5432
    networks:
      - my-network
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@example.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_CONFIG_SERVER_MODE=False   
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    volumes:
      - ./.pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80" 
    depends_on:
      - postgresql
    networks:
      - my-network

  liquibase-migrations:
    container_name: migrations
    image: liquibase/liquibase:4.29
    depends_on:
      - postgresql
    command:
      - --searchPath=/changesets
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/avito
      - --username=user
      - --password=password
      - update
    volumes:
      - ./migrations:/changesets
    networks:
      - my-network
  
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8085:8080"
    volumes:
      - ./api/openapi2/v1/backend.yaml:/foo/swagger.yaml
    environment:
      - SWAGGER_JSON=/foo/swagger.yaml
    networks:
      - my-network

  swagger-ui-grpc:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui-grpc
    ports:
      - "8090:8080"
    volumes:
      - ./api/proto/pvz.swagger.json:/foo/swagger.json
    environment:
      - SWAGGER_JSON=/foo/swagger.json
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    networks:
      - my-network
  
  

networks:
  my-network:
    driver: bridge
