HTTPServer:
  Host: "0.0.0.0"
  Port: "8080"

GRPCServer:
  Host: "localhost"
  Port: "9090"

Gateway:
  Host: "localhost"
  Port: "6060"

Storage:
  Host: "0.0.0.0"
  Port: "5432"
  ssl: "disable"

  MaxConnections: 100
  MinConnections: 20
  MaxLifeTime: 3600
  MaxIdleTime: 300
  HealthCheckPeriod: 30


Cities: Moscow,Kazan,Miami
