swagger: '2.0'
info:
  description: Сервис для управления ПВЗ и приемкой товаров
  title: backend service
  version: 1.0.0
paths:
  /dummyLogin:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: request
          required: true
          schema:
            $ref: '#/definitions/UserLoginRequest'
      responses:
        '200':
          description: Успешная авторизация
          schema:
            $ref: '#/definitions/Token'
        '400':
          description: Неверный запрос
          schema:
            $ref: '#/definitions/Error'
      summary: Получение тестового токена

  /login:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: request
          required: true
          schema:
            $ref: '#/definitions/UserLoginCredentialsRequest'
      responses:
        '200':
          description: Успешная авторизация
          schema:
            $ref: '#/definitions/Token'
        '401':
          description: Неверные учетные данные
          schema:
            $ref: '#/definitions/Error'
      summary: Авторизация пользователя

  /products:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: request
          required: true
          schema:
            $ref: '#/definitions/ProductCreationRequest'
      responses:
        '201':
          description: Товар добавлен
          schema:
            $ref: '#/definitions/Product'
        '400':
          description: Неверный запрос или нет активной приемки
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Доступ запрещен
          schema:
            $ref: '#/definitions/Error'
      security:
        - bearerAuth: []
      summary: Добавление товара в текущую приемку (только для сотрудников ПВЗ)

  /pvz:
    get:
      produces:
        - application/json
      parameters:
        - description: Начальная дата диапазона
          format: date-time
          in: query
          name: startDate
          required: false
          type: string
        - description: Конечная дата диапазона
          format: date-time
          in: query
          name: endDate
          required: false
          type: string
        - default: 1
          description: Номер страницы
          in: query
          minimum: 1
          name: page
          required: false
          type: integer
        - default: 10
          description: Количество элементов на странице
          in: query
          maximum: 30
          minimum: 1
          name: limit
          required: false
          type: integer
      responses:
        '200':
          description: Список ПВЗ
          schema:
            items:
              properties:
                pvz:
                  $ref: '#/definitions/PVZ'
                receptions:
                  items:
                    properties:
                      products:
                        items:
                          $ref: '#/definitions/Product'
                        type: array
                      reception:
                        $ref: '#/definitions/Reception'
                    type: object
                  type: array
              type: object
            type: array
      security:
        - bearerAuth: []
      summary: Получение списка ПВЗ с фильтрацией по дате приемки и пагинацией

    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: request
          required: true
          schema:
            $ref: '#/definitions/PVZCreationRequest'
      responses:
        '201':
          description: ПВЗ создан
          schema:
            $ref: '#/definitions/PVZ'
        '400':
          description: Неверный запрос
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Доступ запрещен
          schema:
            $ref: '#/definitions/Error'
      security:
        - bearerAuth: []
      summary: Создание ПВЗ (только для модераторов)

  '/pvz/{pvzId}/close_last_reception':
    post:
      produces:
        - application/json
      parameters:
        - format: uuid
          in: path
          name: pvzId
          required: true
          type: string
      responses:
        '200':
          description: Приемка закрыта
          schema:
            $ref: '#/definitions/Reception'
        '400':
          description: Неверный запрос или приемка уже закрыта
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Доступ запрещен
          schema:
            $ref: '#/definitions/Error'
      security:
        - bearerAuth: []
      summary: Закрытие последней открытой приемки товаров в рамках ПВЗ

  '/pvz/{pvzId}/delete_last_product':
    post:
      produces:
        - application/json
      parameters:
        - format: uuid
          in: path
          name: pvzId
          required: true
          type: string
      responses:
        '200':
          description: Товар удален
        '400':
          description: 'Неверный запрос, нет активной приемки или нет товаров для удаления'
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Доступ запрещен
          schema:
            $ref: '#/definitions/Error'
      security:
        - bearerAuth: []
      summary: Удаление последнего добавленного товара из текущей приемки (LIFO, только для сотрудников ПВЗ)

  /receptions:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: request
          required: true
          schema:
            $ref: '#/definitions/ReceptionCreationRequest'
      responses:
        '201':
          description: Приемка создана
          schema:
            $ref: '#/definitions/Reception'
        '400':
          description: Неверный запрос или есть незакрытая приемка
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Доступ запрещен
          schema:
            $ref: '#/definitions/Error'
      security:
        - bearerAuth: []
      summary: Создание новой приемки товаров (только для сотрудников ПВЗ)

  /register:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: request
          required: true
          schema:
            $ref: '#/definitions/UserRegistrationRequest'
      responses:
        '201':
          description: Пользователь создан
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Неверный запрос
          schema:
            $ref: '#/definitions/Error'
      summary: Регистрация пользователя

definitions:
  Error:
    properties:
      message:
        type: string
    required:
      - message
    type: object
  PVZ:
    properties:
      city:
        enum:
          - Москва
          - Санкт-Петербург
          - Казань
        type: string
      id:
        format: uuid
        type: string
      registrationDate:
        format: date-time
        type: string
    required:
      - city
    type: object
  Product:
    properties:
      dateTime:
        format: date-time
        type: string
      id:
        format: uuid
        type: string
      receptionId:
        format: uuid
        type: string
      type:
        enum:
          - электроника
          - одежда
          - обувь
        type: string
    required:
      - type
      - receptionId
    type: object
  Reception:
    properties:
      dateTime:
        format: date-time
        type: string
      id:
        format: uuid
        type: string
      pvzId:
        format: uuid
        type: string
      status:
        enum:
          - in_progress
          - close
        type: string
    required:
      - dateTime
      - pvzId
      - status
    type: object
  Token:
    type: string
  User:
    properties:
      email:
        format: email
        type: string
      id:
        format: uuid
        type: string
      role:
        enum:
          - employee
          - moderator
        type: string
    required:
      - email
      - role
    type: object
  UserLoginRequest:
    properties:
      role:
        enum:
          - employee
          - moderator
        type: string
    required:
      - role
    type: object
  UserLoginCredentialsRequest:
    properties:
      email:
        format: email
        type: string
      password:
        type: string
    required:
      - email
      - password
    type: object
  ProductCreationRequest:
    properties:
      pvzId:
        format: uuid
        type: string
      type:
        enum:
          - электроника
          - одежда
          - обувь
        type: string
    required:
      - type
      - pvzId
    type: object
  PVZCreationRequest:
    properties:
      city:
        enum:
          - Москва
          - Санкт-Петербург
          - Казань
        type: string
      registrationDate:
        format: date-time
        type: string
    required:
      - city
    type: object
  ReceptionCreationRequest:
    properties:
      pvzId:
        format: uuid
        type: string
    required:
      - pvzId
    type: object
  UserRegistrationRequest:
    properties:
      email:
        format: email
        type: string
      password:
        type: string
      role:
        enum:
          - employee
          - moderator
        type: string
    required:
      - email
      - password
      - role
    type: object
securityDefinitions:
  bearerAuth:
    in: header
    name: Authorization
    type: apiKey
